name: Main
on:
   push:
     branches: [ master ]
   workflow_dispatch:
jobs:
   build:
     runs-on: ubuntu-latest

     steps:
       - uses: actions/checkout@v3
       - name: Use Node.js
         uses: actions/setup-node@v3
         with: 
           node-version: "14.x"
       - name: Install dependencies
         working-directory: ./api
         run: yarn install
       - name: Run Test
         working-directory: ./api
         run: yarn run build
